### ISSUE TITLE
database installation sequence 

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#114]
What is the correct sequence to run database scripts v1 and v2??
when run db\beta-1\v1\mixerp.sql and run db\beta-1\v2\mixerp-patch-for-v1.sql
some tables is empty such as users and office and other

**Comment by mixerp** [comment]
Hi @nubiancc,

There are two cases.

**Case 1 : Upgrading Existing Database**

If you have already installed Beta 1 Version 1 and you want to upgrade to the latest version, run the file:

**v2/mixerp-patch-for-v1.sql**

This patch file will automatically and safely update your database from Beta 1 Version 1 to current version without any loss of data.

**Case 2 : Creating a New Database**
Depending upon what is desired, **one these files** can be used from the **v2** directory:

**mixerp-incremental-sample.sql**
This files contains everything, plus sample data, up to this point of time. This includes everything from Beta 1 Version 1. So, just running this file is fine if you want sample data.

**mixerp-incremental-blank-db.sql**
This file contains everything from Beta 1 Version 1, plus an upgrade to current and correct development database version. So, just running this file is fine if you want MixERP database, but without any sample data.

**Please Note**
Since Beta 1 Version 2 is under development, Case 1 does not make a practical sense since there might be broken features and issues with development version. For development and testing scenario, both approach is okay.

Please feel free to comment if you have further questions regarding this issue.

**Comment by nubiancc** [comment]
Hi Mixerp
 after backup database and download it , how can i restore database form mixerp consol

**Comment by mixerp** [comment]
Restore is an offline task, so it should be done manually using pgAdmin:

http://www.pgadmin.org/docs/1.16/restore.html
