### ISSUE TITLE
"GoToBottom was not found" in top selling items.

### ISSUE THREAD

**Issue by ghost** [mixerp/mixerp#318]
![sales report](https://cloud.githubusercontent.com/assets/10184034/8507939/556fb01c-2279-11e5-85aa-72ec494ada0e.png)

**Comment by mixerp** [comment]
Could you please make sure that you have updated your database along with the code?

**Comment by Johann-Schwarz** [comment]
Sorry not from me.

**Comment by Johann-Schwarz** [comment]
GotoBottom   and Filter are new items regarding language list. They are only existing in English but are empty in other languages. as I had to update German items yesterday. My question is How can I update all the other languages. Because I would do that. An other problem is : Is DB Server Config done correctly as I had that error still after updating my database but the configuration pointed to 'mixerp' and not to mine which is called 'company'

**Comment by mixerp3** [comment]
Solved.
