### ISSUE TITLE
Opening Accounts Balance

### ISSUE THREAD

**Issue by nubiancc** [mixerp/mixerp#329]
how can add Opening Accounts Balance when start work in Mixerp ? 
how can I close the end of year Operations (Close Accounts, Close Inventory, Closing Entries, etc...)?
notce: Closing Entries must be generated automaticly?

http://accountingexplained.com/financial/cycle/closing-entries

**Comment by nubiancc** [comment]
The valuation of ending inventory is done using FIFO, LIFO, AVCO or specific identification methods under either periodic inventory system or under perpetual inventory system.

**Comment by nubiancc** [comment]
Cost of Inventory

When inventory is purchased, the cost of inventory includes the purchase price, delivery costs, excise and custom duties etc. less any discount that is obtained. When inventory is manufactured, its cost includes the production cost plus any cost which is incured on making the inventory saleable for example packing cost.

However if abnormal cost is incurred on delivery or handling etc. then only normal portion will be added to the cost of inventory. The rest should be expensed.

**Comment by Johann-Schwarz** [comment]
Hi !
Sorry but this in my eyes is more a question for the user forums then to be a bug. The value of a stock is not only depending on the items original price, the items also can be invalidated because of their age, so this is something YOU have to decide when starting to enter the amount of items and the value they actually may have independent of their original costs when they had been purchased as new items.
Example: I have had  a television in my shop bought for about 2500 Euros. One year later there had still been 5 of them on stock, but nobody obviously was interested to buy an 'old' television, because there are already TV's on the market much bigger screen, much cheaper. So it was invalidated to a value of 900 Euros / piece. Has nothing to do with what this all has cost. The loss was booked as  costs and reduced the win in the year just ended.

**Comment by mixerp3** [comment]
Question.
