### ISSUE TITLE
Getting Menu Issue

### ISSUE THREAD

**Issue by asherjawad** [mixerp/mixerp#459]
When I click on any menu its goes into ...http://localhost/module/etc.mix and showing not found

I have downloaded 1.4 / For Visual Studio 2013

**Comment by mixerp** [comment]
Since this is not an issue but a question, please do post your question in [mixerp forums](https://mixerp.org/erp/forum/) instead of here.

- The v1.4 should only be used to bug fixing, not development. 
- You need to install VS2015.
- It seems that you missed to read the [developer documentation], especially the first two chapters [cloning mixerp](http://docs.mixerp.org/docs/developer/clone-mixerp.html) and [creating iis application](http://docs.mixerp.org/docs/developer/create-iis-application.html)
- I would emphasize that *you must think about git* before you even think about Visual Studio or PostgreSQL.
