### ISSUE TITLE
Log in attempt issue, after cloning the latest code

### ISSUE THREAD

**Issue by MohammadSalah** [mixerp/mixerp#467]
I've cloned the latest source code from the repository, when I run it and try to login, I get the following error

"function office.sign_in(integer, unknown, unknown, unknown, unknown, integer, unknown) does not exist"

i  believe this is related to the menu bug that was fixed week ago, the function in the DB is expecting a challenge parameter, but you no longer send it, the code that was change is in the Services/user.asmx  => Authenticate method

by the way, what is the latest  stable release that one can build on top of it. and is there documentation on how to setup all the modules, or where to start ?

**Comment by mixerp** [comment]
You are right. Thank for you pointing this out. The SQL bundling was missed in last commit. What you can do is navigate to this folder on your local repository:

`https://github.com/mixerp/mixerp/tree/master/src/FrontEnd/db/1.x/1.6`

and run these two batch files:
1. rebundle-db-with-sample.bat
2. rebundle-db-without-sample.bat

Running the above files will recreate SQL bundled files. Now, depending on how you want to create your database, use one of these two:

1.  mixerp-incremental-blank-db.sql
2. mixerp-incremental-sample.sql

or just run the file:

`mixerp-patch-for-1.5.sql` 

if you want to update the existing database. Don't worry because you can run a `SQL patch file` multiple times, which will not create any side effects or data loss.

**Comment by MohammadSalah** [comment]
thank you for your reply, it worked :+1:
