### ISSUE TITLE
Datestyle - Execute query for other datastyle settings

### ISSUE THREAD

**Issue by machmet** [mixerp/mixerp#62]
Welcom,
I have setings this datastyle
SELECT '2014-07-17'::date
but in sql is settings
SELECT '7/17/2014'::date
When I traing change datastyle is not working.
ALTER DATABASE mixerp SET datestyle TO "ISO, MDY";

I add and working in 3 line
SET datestyle TO "ISO, MDY";

**Comment by binodnp** [comment]
Machmet, are you referring to Plpgunit or MixERP database settings?

**Comment by machmet** [comment]
From that I should start.
I can correct script and i trying set datcollate and datctype.
To Polish_Poland.1250.

https://raw.githubusercontent.com/machmet/mixerp/2b76c8db83d40b0fe0e805ad1d80502ab8dbf37f/src/FrontEnd/MixERP.Net.FrontEnd/db/mixerp.pl-PL.sql

**Comment by mixerp** [comment]
Hi machmet:

We support various locale on the application level (asp.net). The backend collation, however, must be "UTF-8 United States" as of now. Please have a look on PostgreSQL documentation on changing the locale settings on the query level.

http://www.postgresql.org/docs/9.1/static/locale.html

Regarding the translation, the file mixerp.pl-PL.sql should not be created manually because we bundle SQL files. Instead of that, you would want to create a new dictionary file for pl-PL on:

/src/FrontEnd/MixERP.Net.FrontEnd/db/src:dictionary/pl-PL.dict

Once you have the dictionary file containing the translation in polish, you will have to edit the file:

/src/FrontEnd/MixERP.Net.FrontEnd/db/mixerp.sqlbundle

to add polish language. The culture (date, currency, and number format) will be automatically handled by the frontend.

We are releasing the first beta today, and we will be creating a localization importer and guide for additional language support in MixERP within a week of the release.

So, I would kindly advise you to stay tuned to MixERP forums and blog.

Nice to hear from you. Good day.
